# Generated by Django 3.2.6 on 2021-09-04 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('vendido', 'vendido'), ('siniestro', 'siniestro'), ('pendiente', 'pendiente'), ('propietario', 'propietario')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.PositiveIntegerField()),
                ('cilindraje', models.PositiveIntegerField()),
                ('foto_moto', models.ImageField(upload_to='fotos_motos')),
                ('color', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=100, unique=True)),
                ('chasis', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios')),
                ('cedula', models.PositiveIntegerField(unique=True)),
                ('telefono', models.PositiveIntegerField(blank=True, null=True)),
                ('dirección', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('descripción', models.TextField(blank=True, null=True)),
                ('id_historial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motos.historial')),
            ],
        ),
        migrations.AddField(
            model_name='historial',
            name='moto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motos.moto'),
        ),
        migrations.AddField(
            model_name='historial',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motos.persona'),
        ),
    ]
