# Generated by Django 3.2.6 on 2021-09-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0002_auto_20210904_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
    ]
